spring.application.name=MBC_TicketReserve

spring.main.web-application-type=servlet
server.port=8080

#profile
spring.profiles.include=db, aws, OAuth, payment, MAIL


### JPA Setting  ####
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

## Logging  Setting
logging.level.org.hibernate=info

## Thymelead  Cache  Setting
spring.thymeleaf.cache=false

# 파일 첨부 하기와 사이즈 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# 세션 타임아웃 1일로
server.servlet.session.timeout=24h


### JSP 경로 설정 ###
#spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.view.suffix=.jsp